k: 1.6
k_nuc: 4
g: 2
T: 500
T_nuc: 1
act_slope: 0.03
adh_sigma: 5
adh_basal: 0.3
adh_frac: 0.03
adh_num: 50
R0: 20
R_nuc: 1
dyn_basal: 0.9
prop_factor: 1
dyn_norm_k: 1.0 # Not tested
dyn_sigma: 1.0 # Not tested
dyn_kernel_size: 5 # Not tested
DA: 0.0003333333
DI: 0.0333333333
k0: 0.10
k0_min: 0.01
k0_scalar: 10
gamma: 1
delta: 1
A0: 0.4
s1: 0.7
s2: 0.05
F0: 0.5
kn: 1
ks: 0.25
eps: 0.1
dt: 3.75e-4
dx: 7.0755e-3
A_max: 0.67
A_min: 0.044
AC_max: 0.67
AC_min: 0.044
sim_rows: 1500
sim_cols: 600
seed: 0
num_iters: 500000
frame_padding: 20
diff_t: 100
save_t: 1000
adh_t: 200
fr_t: 50
